### ISSUE TITLE
Status on rf_btns branch

### ISSUE THREAD

**Issue by A-T-Kristensen** [strath-sdr/pynq_agc#7]
Hello,

I am interested in your RF automatic gain control on the branch https://github.com/strath-sdr/pynq_agc/tree/rf_btns 

Since it is not on the master, I was curious as to whether it works on the ZCU111 board yet?

Regards,
Andreas

**Comment by cramsay** [comment]
Hi Andreas,

I think you're in luck! If I recall correctly, the `rf_btns` branch was developed on the ZCU111 and should be working OK. It'll be merged into master once it has been tested on the other boards.

Let us know how you get on with it.

Cheers,
Craig

**Comment by A-T-Kristensen** [comment]
Hi Craig,

Thanks for the quick reply, I'll give it a try.

Regards,
Andreas
